import { useState } from 'react';
import { AiService } from '../../../services/AiService';

export function useDiscovery(showToast, allLeads, setAllLeads) {
    const [isSearching, setIsSearching] = useState(false);
    const [searchPrompt, setSearchPrompt] = useState('');
    const [discoveredData, setDiscoveredData] = useState([]);

    const handleSearchClick = async () => {
        if (!searchPrompt.trim()) return;
        setIsSearching(true);
        showToast('Initiating NVIDIA AI Search...');

        try {
            const results = await AiService.discoverLeads(searchPrompt);
            setDiscoveredData(results);
            showToast(`Search complete. Found ${results.length} highly qualified prospects.`);
        } catch (error) {
            console.error("AI Search Error:", error);
            showToast('Error communicating with AI Service.');
        } finally {
            setIsSearching(false);
        }
    };

    const handleAddToCRM = (prospect) => {
        const newLead = {
            id: `L${String(allLeads.length + 1).padStart(3, '0')}`,
            company: prospect.company,
            contact: 'TBD',
            phone: '',
            email: 'contact@' + prospect.company.toLowerCase().replace(/[^a-z0-9]/g, '') + '.com',
            stage: 'New Lead',
            product: 'Determining needs...',
            qty: 0,
            value: prospect.matchScore > 90 ? 500000 : 150000,
            source: 'AI Lead Discovery',
            assignedTo: 'AI Agent',
            lastActivity: new Date().toISOString().split('T')[0],
            notes: `Auto-generated by AI Discovery.\nMatch Score: ${prospect.matchScore}%\nIndustry: ${prospect.industry}\nIntent: ${prospect.intent}`
        };

        setAllLeads([...allLeads, newLead]);
        showToast(`✅ ${prospect.company} added to CRM Pipeline!`);

        setDiscoveredData(prev => prev.filter(p => p.id !== prospect.id));
    };

    return {
        isSearching,
        searchPrompt,
        setSearchPrompt,
        discoveredData,
        handleSearchClick,
        handleAddToCRM
    };
}
